name: TaskTimeFlow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate structure
        run: |
          echo "🔍 Validating TaskTimeFlow repository structure..."
          
          # Check main structure
          echo "📁 Repository root:"
          ls -la
          
          echo ""
          echo "📁 Apps directory:"
          ls -la apps/ 2>/dev/null || echo "⚠️  Apps directory not found"
          
          echo ""
          echo "📁 Web app:"
          ls -la apps/web/ 2>/dev/null || echo "⚠️  Web app directory not found"
          
          echo ""
          echo "📁 Packages:"
          ls -la packages/ 2>/dev/null || echo "⚠️  Packages directory not found"
          
          echo ""
          echo "✅ Structure validation complete"

      - name: Check essential files
        run: |
          echo "🔍 Checking essential files..."
          
          files=(
            "README.md"
            "package.json" 
            "apps/web/package.json"
            "apps/web/next.config.js"
            "apps/web/app/page.tsx"
            "docs/requirements.md"
          )
          
          for file in "${files[@]}"; do
            if [ -f "$file" ]; then
              echo "✅ $file exists"
            else
              echo "⚠️  $file missing"
            fi
          done
          
          echo ""
          echo "🎉 TaskTimeFlow repository is ready!"